## 1. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,7,13,105])
print(f"Memory size:{arr.nbytes}")

Memory size:32

## 2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

In [40]:
arr6=np.array([1,10,2,120,20,405,45])
print(arr6[arr6>10])
print(arr6[arr6>=10])
print(arr6[arr6<10])
print(arr6[arr6<=10])

[120  20 405  45]
[ 10 120  20 405  45]
[1 2]
[ 1 10  2]

## 3. Write a NumPy program to create an array of integers from 50 to 95.

In [4]:
arr2 = np.arange(50,96)
arr2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])

## 4. Write a NumPy program to create an array of all even integers from 20 to 80.

In [8]:
arr3 = np.arange(20,81,2)
arr3

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80])

## 5. Write a NumPy program to generate an array of 10 random numbers from 30 to 50.

In [13]:
arr4 = np.random.randint(30,50,10)
arr4

array([32, 39, 35, 40, 47, 48, 47, 42, 32, 32], dtype=int32)

## 6. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [25]:
arr5 = np.arange(20,51)
print(arr5 % 3)

[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]

## 7. Write a Pandas program to add, subtract, multiple and divide two Pandas Series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [17]:
import pandas as pd

In [18]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

In [20]:
print(f"Addition: {s1+s2}")

Addition: 0     3
1     7
2    11
3    15
4    19
dtype: int64

In [22]:
print(f"Subtraction: {s1-s2}")

Subtraction: 0    1
1    1
2    1
3    1
4    1
dtype: int64

In [23]:
print(f"Multiplication: {s1*s2}")

Multiplication: 0     2
1    12
2    30
3    56
4    90
dtype: int64

In [24]:
print(f"Division: {s1/s2}")

Division: 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

## 8. Write a Pandas program to convert a NumPy array to a Pandas series.

In [27]:
arr = np.array([1,2,3,4,5])
series = pd.Series(arr)
print(type(series))

<class 'pandas.core.series.Series'>

## 9. Write a Pandas program to change the data type of given a column or a Series.

In [4]:
import pandas as pd
data = {'Age': ['20', '25', '30', '35']}
df = pd.DataFrame(data)
print("Before conversion:")
print(df)
print(df.dtypes)
df['Age'] = df['Age'].astype(int)
print("After conversion:")
print(df)
print(df.dtypes)
import pandas as pd

s = pd.Series(['1', '2', '3', '4'])
print("Before conversion:")
print(s)
print(s.dtype)
s = s.astype(float)
print("\nAfter conversion:")
print(s)
print(s.dtype)

Before conversion:
  Age
0  20
1  25
2  30
3  35
Age    object
dtype: object
After conversion:
   Age
0   20
1   25
2   30
3   35
Age    int64
dtype: object
Before conversion:
0    1
1    2
2    3
3    4
dtype: object
object

After conversion:
0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64
float64

## 10.

In [6]:
#1
empid = [1,2,3,4,5,6,7,8,9,10]
empname=["abc","pqr","pr","qr","pq","prr","qqr","zyx","xyz","zzz"]

In [39]:
#2
s1 = pd.Series(empid)
s2 = pd.Series(empname)

In [40]:
#3
type(s1)
type(s2)

pandas.core.series.Series

In [41]:
#4
df2=pd.DataFrame({"EmpID": empid,"Name": empname})

In [42]:
##5
print(df2)

   EmpID Name
0      1  abc
1      2  pqr
2      3   pr
3      4   qr
4      5   pq
5      6  prr
6      7  qqr
7      8  zyx
8      9  xyz
9     10  zzz

In [43]:
df2.head(5)

   EmpID Name
0      1  abc
1      2  pqr
2      3   pr
3      4   qr
4      5   pq

In [45]:
df2.tail(5)

   EmpID Name
5      6  prr
6      7  qqr
7      8  zyx
8      9  xyz
9     10  zzz

In [46]:
df2.head(2)

   EmpID Name
0      1  abc
1      2  pqr

In [47]:
df2.tail(2)

   EmpID Name
8      9  xyz
9     10  zzz

In [49]:
print(df2.loc[4,"Name"])

pq

In [52]:
print(df.loc[3])

0    pr
Name: 3, dtype: object

In [53]:
df.to_csv("MyRecord.csv", index=False)

## 11. Consider mtcars.csv file  and plot the following graphs.

In [55]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns